spring:
  application:
    name: sample-config-server
  cloud:
      config:
        server:
          git:
            uri: https://github.com/panneerTrails/pan-config.git
            #username: panneerselvam.sn@gmail.com
            #password: Dhanya@2016
server:
  port: 8888